Repository nanoframework/System.Runtime.Serialization, pull requests merged in 2025-02, with the labels that each got.

#28 Fix nullt ypereference error for big .NET helper
  nanoFramework.Serialization.Helper/BinaryFormatter.cs
Labels: Type: Bug

#29 Rework AZDO yaml to build and publish helper and library
  azure-pipelines.yml
Labels: Area: Config-and-Build

#30 Update dependencies
  Tests/HelperTests/HelperTests.csproj
  Tests/HelperTests/packages.lock.json
  nanoFramework.Serialization.Helper/nanoFramework.Serialization.Helper.csproj
  nanoFramework.Serialization.Helper/packages.lock.json
Labels: Type: dependencies
